### ISSUE TITLE
EXP - Erreur Python en cas de description nulle

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature-GIS#42]
Une erreur Python est retournée si l'export présente une valeur nulle sur le champ "desc"

```
2024-09-09T16:44:43     WARNING    Traceback (most recent call last):
              File "C:\Users/maxime.toma/AppData/Roaming/QGIS/QGIS3\profiles\maxime/python/plugins\GeoNature-GIS\export_dialog.py", line 97, in openSelectExport
              return self.connexionSelect.selected_export_name , self.connexionSelect.description , self.connexionSelect.selected_view_schema, self.connexionSelect.selected_view_name, self.connexionSelect.geom_field, self.connexionSelect.srid, self.connexionSelect.pk_column, self.maj_lbl_nom_export(), self.maj_lbl_description()
              File "C:\Users/maxime.toma/AppData/Roaming/QGIS/QGIS3\profiles\maxime/python/plugins\GeoNature-GIS\export_dialog.py", line 118, in maj_lbl_description
              self.lbl_viewdescription.setText(description)
             TypeError: setText(self, str): argument 1 has unexpected type 'QVariant'
```

**Comment by maximetoma** [comment]
Fait dans la 1.2.0
